/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ActivityEntry = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'moduleName' : IDL.Text,
  'userId' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Person = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'avatarInitials' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'department' : IDL.Text,
});
export const AuthUser = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'principal' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'createdAt' : IDL.Opt(IDL.Int),
  'role' : IDL.Variant({
    'member' : IDL.Null,
    'admin' : IDL.Null,
    'owner' : IDL.Null,
    'guest' : IDL.Null,
  }),
  'email' : IDL.Text,
  'avatarColor' : IDL.Text,
  'department' : IDL.Text,
  'lastLogin' : IDL.Opt(IDL.Int),
});
export const Calendar = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'visible' : IDL.Bool,
});
export const CalendarEvent = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'allDay' : IDL.Bool,
  'color' : IDL.Text,
  'description' : IDL.Text,
  'calendarId' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const Channel = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'workspaceId' : IDL.Nat,
});
export const UserId = IDL.Nat;
export const Document = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'workspaceId' : IDL.Nat,
  'folderId' : IDL.Opt(IDL.Nat),
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'folderId' : IDL.Opt(IDL.Nat),
});
export const NoteFolder = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const Presentation = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'ownerId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'color' : IDL.Text,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
});
export const ProjectMilestone = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Int),
  'projectId' : IDL.Nat,
});
export const Sheet = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const Slide = IDL.Record({
  'id' : IDL.Nat,
  'visualType' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'presentationId' : IDL.Nat,
  'position' : IDL.Nat,
});
export const TaskPriority = IDL.Variant({
  'low' : IDL.Null,
  'normal' : IDL.Null,
  'high' : IDL.Null,
  'urgent' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'done' : IDL.Null,
  'blocked' : IDL.Null,
  'todo' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'dueDate' : IDL.Opt(Timestamp),
  'description' : IDL.Text,
  'assigneeIds' : IDL.Vec(UserId),
  'projectId' : IDL.Opt(IDL.Nat),
  'priority' : TaskPriority,
  'listId' : IDL.Nat,
});
export const DirectMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'toUserId' : UserId,
  'fromUserId' : UserId,
});
export const Folder = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'workspaceId' : IDL.Nat,
  'parentId' : IDL.Opt(IDL.Nat),
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'channelId' : IDL.Nat,
  'authorId' : UserId,
  'createdAt' : Timestamp,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'notifType' : IDL.Variant({
    'update' : IDL.Null,
    'mention' : IDL.Null,
    'activity' : IDL.Null,
  }),
  'body' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'sourceId' : IDL.Opt(IDL.Nat),
  'isRead' : IDL.Bool,
  'sourceType' : IDL.Opt(IDL.Text),
});
export const SheetCell = IDL.Record({
  'col' : IDL.Nat,
  'row' : IDL.Nat,
  'value' : IDL.Text,
  'sheetId' : IDL.Nat,
});
export const TaskList = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'projectId' : IDL.Opt(IDL.Nat),
  'workspaceId' : IDL.Nat,
  'isPersonal' : IDL.Bool,
});
export const User = IDL.Record({
  'id' : UserId,
  'title' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Variant({
    'member' : IDL.Null,
    'admin' : IDL.Null,
    'owner' : IDL.Null,
    'guest' : IDL.Null,
  }),
  'email' : IDL.Text,
  'avatarColor' : IDL.Text,
  'department' : IDL.Text,
});
export const UserSettings = IDL.Record({
  'theme' : IDL.Text,
  'notificationsEnabled' : IDL.Bool,
  'displayName' : IDL.Text,
  'email' : IDL.Text,
});
export const Workspace = IDL.Record({
  'id' : IDL.Nat,
  'ownerId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'memberIds' : IDL.Vec(UserId),
});
export const WorkspaceSettings = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addActivity' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ActivityEntry],
      [],
    ),
  'addPerson' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Person],
      [],
    ),
  'assignMemberRole' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
  'clearSheetCell' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'completeOnboarding' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [AuthUser],
      [],
    ),
  'createCalendar' : IDL.Func([IDL.Text, IDL.Text], [Calendar], []),
  'createCalendarEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Bool, IDL.Text, IDL.Nat],
      [CalendarEvent],
      [],
    ),
  'createChannel' : IDL.Func([IDL.Text, IDL.Text], [Channel], []),
  'createDocument' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat)], [Document], []),
  'createNote' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat)], [Note], []),
  'createNoteFolder' : IDL.Func([IDL.Text], [NoteFolder], []),
  'createPresentation' : IDL.Func([IDL.Text], [Presentation], []),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Project],
      [],
    ),
  'createProjectMilestone' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Int)],
      [ProjectMilestone],
      [],
    ),
  'createSheet' : IDL.Func([IDL.Text], [Sheet], []),
  'createSlide' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [Slide],
      [],
    ),
  'createTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Opt(IDL.Int),
        TaskPriority,
        TaskStatus,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Nat),
      ],
      [Task],
      [],
    ),
  'deleteCalendarEvent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteNoteFolder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePresentation' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProjectMilestone' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSheet' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSlide' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getActivityFeed' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(ActivityEntry)],
      ['query'],
    ),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCalendarEvents' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(CalendarEvent)],
      ['query'],
    ),
  'getCalendars' : IDL.Func([], [IDL.Vec(Calendar)], ['query']),
  'getChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'getDirectMessages' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(DirectMessage)],
      ['query'],
    ),
  'getDocument' : IDL.Func([IDL.Nat], [IDL.Opt(Document)], ['query']),
  'getDocuments' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(Document)], ['query']),
  'getFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
  'getMe' : IDL.Func([], [IDL.Opt(AuthUser)], ['query']),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
  'getNoteFolders' : IDL.Func([], [IDL.Vec(NoteFolder)], ['query']),
  'getNotes' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(Note)], ['query']),
  'getNotifications' : IDL.Func([IDL.Nat], [IDL.Vec(Notification)], ['query']),
  'getPeople' : IDL.Func([], [IDL.Vec(Person)], ['query']),
  'getPerson' : IDL.Func([IDL.Nat], [IDL.Opt(Person)], ['query']),
  'getPresentation' : IDL.Func([IDL.Nat], [IDL.Opt(Presentation)], ['query']),
  'getPresentationSlides' : IDL.Func([IDL.Nat], [IDL.Vec(Slide)], ['query']),
  'getPresentations' : IDL.Func([], [IDL.Vec(Presentation)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getProjectMilestones' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProjectMilestone)],
      ['query'],
    ),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getSheet' : IDL.Func([IDL.Nat], [IDL.Opt(Sheet)], ['query']),
  'getSheetCells' : IDL.Func([IDL.Nat], [IDL.Vec(SheetCell)], ['query']),
  'getSheets' : IDL.Func([], [IDL.Vec(Sheet)], ['query']),
  'getTaskLists' : IDL.Func([], [IDL.Vec(TaskList)], ['query']),
  'getTasks' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'getUser' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
  'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getWorkspace' : IDL.Func([], [IDL.Opt(Workspace)], ['query']),
  'getWorkspaceMembers' : IDL.Func([], [IDL.Vec(AuthUser)], ['query']),
  'getWorkspaceSettings' : IDL.Func([], [WorkspaceSettings], ['query']),
  'isOnboarded' : IDL.Func([], [IDL.Bool], ['query']),
  'joinWithInviteCode' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(AuthUser)],
      [],
    ),
  'markAllNotificationsRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [AuthUser], []),
  'removeMember' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'removeMemberByPrincipal' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'renamePresentation' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(Presentation)],
      [],
    ),
  'renameSheet' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Sheet)], []),
  'reorderSlides' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [IDL.Vec(Slide)], []),
  'sendDirectMessage' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [DirectMessage],
      [],
    ),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [Message], []),
  'setSheetCell' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [SheetCell],
      [],
    ),
  'toggleCalendarVisibility' : IDL.Func([IDL.Nat], [IDL.Opt(Calendar)], []),
  'toggleProjectMilestone' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ProjectMilestone)],
      [],
    ),
  'updateCalendarEvent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Bool, IDL.Text],
      [IDL.Opt(CalendarEvent)],
      [],
    ),
  'updateDocument' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Opt(Document)],
      [],
    ),
  'updateMember' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(Person)],
      [],
    ),
  'updateMyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateNote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Opt(Note)], []),
  'updatePersonStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Person)], []),
  'updateProject' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(Project)],
      [],
    ),
  'updateProjectMilestone' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Int)],
      [IDL.Opt(ProjectMilestone)],
      [],
    ),
  'updateSlide' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(Slide)],
      [],
    ),
  'updateTask' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Opt(IDL.Int),
        TaskPriority,
        TaskStatus,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Opt(Task)],
      [],
    ),
  'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [IDL.Opt(Task)], []),
  'updateUserSettings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
      [UserSettings],
      [],
    ),
  'updateWorkspaceSettings' : IDL.Func(
      [IDL.Text, IDL.Text],
      [WorkspaceSettings],
      [],
    ),
  'whoAmI' : IDL.Func([], [IDL.Principal], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ActivityEntry = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'moduleName' : IDL.Text,
    'userId' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Person = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'avatarInitials' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'department' : IDL.Text,
  });
  const AuthUser = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'principal' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : IDL.Opt(IDL.Int),
    'role' : IDL.Variant({
      'member' : IDL.Null,
      'admin' : IDL.Null,
      'owner' : IDL.Null,
      'guest' : IDL.Null,
    }),
    'email' : IDL.Text,
    'avatarColor' : IDL.Text,
    'department' : IDL.Text,
    'lastLogin' : IDL.Opt(IDL.Int),
  });
  const Calendar = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'visible' : IDL.Bool,
  });
  const CalendarEvent = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'allDay' : IDL.Bool,
    'color' : IDL.Text,
    'description' : IDL.Text,
    'calendarId' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const Channel = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'workspaceId' : IDL.Nat,
  });
  const UserId = IDL.Nat;
  const Document = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'workspaceId' : IDL.Nat,
    'folderId' : IDL.Opt(IDL.Nat),
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'folderId' : IDL.Opt(IDL.Nat),
  });
  const NoteFolder = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const Presentation = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'ownerId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'color' : IDL.Text,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  const ProjectMilestone = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Int),
    'projectId' : IDL.Nat,
  });
  const Sheet = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const Slide = IDL.Record({
    'id' : IDL.Nat,
    'visualType' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'presentationId' : IDL.Nat,
    'position' : IDL.Nat,
  });
  const TaskPriority = IDL.Variant({
    'low' : IDL.Null,
    'normal' : IDL.Null,
    'high' : IDL.Null,
    'urgent' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'done' : IDL.Null,
    'blocked' : IDL.Null,
    'todo' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'dueDate' : IDL.Opt(Timestamp),
    'description' : IDL.Text,
    'assigneeIds' : IDL.Vec(UserId),
    'projectId' : IDL.Opt(IDL.Nat),
    'priority' : TaskPriority,
    'listId' : IDL.Nat,
  });
  const DirectMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'toUserId' : UserId,
    'fromUserId' : UserId,
  });
  const Folder = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'workspaceId' : IDL.Nat,
    'parentId' : IDL.Opt(IDL.Nat),
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'channelId' : IDL.Nat,
    'authorId' : UserId,
    'createdAt' : Timestamp,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'notifType' : IDL.Variant({
      'update' : IDL.Null,
      'mention' : IDL.Null,
      'activity' : IDL.Null,
    }),
    'body' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'sourceId' : IDL.Opt(IDL.Nat),
    'isRead' : IDL.Bool,
    'sourceType' : IDL.Opt(IDL.Text),
  });
  const SheetCell = IDL.Record({
    'col' : IDL.Nat,
    'row' : IDL.Nat,
    'value' : IDL.Text,
    'sheetId' : IDL.Nat,
  });
  const TaskList = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'projectId' : IDL.Opt(IDL.Nat),
    'workspaceId' : IDL.Nat,
    'isPersonal' : IDL.Bool,
  });
  const User = IDL.Record({
    'id' : UserId,
    'title' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Variant({
      'member' : IDL.Null,
      'admin' : IDL.Null,
      'owner' : IDL.Null,
      'guest' : IDL.Null,
    }),
    'email' : IDL.Text,
    'avatarColor' : IDL.Text,
    'department' : IDL.Text,
  });
  const UserSettings = IDL.Record({
    'theme' : IDL.Text,
    'notificationsEnabled' : IDL.Bool,
    'displayName' : IDL.Text,
    'email' : IDL.Text,
  });
  const Workspace = IDL.Record({
    'id' : IDL.Nat,
    'ownerId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'memberIds' : IDL.Vec(UserId),
  });
  const WorkspaceSettings = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addActivity' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ActivityEntry],
        [],
      ),
    'addPerson' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Person],
        [],
      ),
    'assignMemberRole' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
    'clearSheetCell' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'completeOnboarding' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [AuthUser],
        [],
      ),
    'createCalendar' : IDL.Func([IDL.Text, IDL.Text], [Calendar], []),
    'createCalendarEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Bool, IDL.Text, IDL.Nat],
        [CalendarEvent],
        [],
      ),
    'createChannel' : IDL.Func([IDL.Text, IDL.Text], [Channel], []),
    'createDocument' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat)], [Document], []),
    'createNote' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat)], [Note], []),
    'createNoteFolder' : IDL.Func([IDL.Text], [NoteFolder], []),
    'createPresentation' : IDL.Func([IDL.Text], [Presentation], []),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Project],
        [],
      ),
    'createProjectMilestone' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Int)],
        [ProjectMilestone],
        [],
      ),
    'createSheet' : IDL.Func([IDL.Text], [Sheet], []),
    'createSlide' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Slide],
        [],
      ),
    'createTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Opt(IDL.Int),
          TaskPriority,
          TaskStatus,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Nat),
        ],
        [Task],
        [],
      ),
    'deleteCalendarEvent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteNoteFolder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePresentation' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProjectMilestone' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSheet' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSlide' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getActivityFeed' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(ActivityEntry)],
        ['query'],
      ),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCalendarEvents' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(CalendarEvent)],
        ['query'],
      ),
    'getCalendars' : IDL.Func([], [IDL.Vec(Calendar)], ['query']),
    'getChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'getDirectMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(DirectMessage)],
        ['query'],
      ),
    'getDocument' : IDL.Func([IDL.Nat], [IDL.Opt(Document)], ['query']),
    'getDocuments' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'getFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
    'getMe' : IDL.Func([], [IDL.Opt(AuthUser)], ['query']),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
    'getNoteFolders' : IDL.Func([], [IDL.Vec(NoteFolder)], ['query']),
    'getNotes' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(Note)], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPeople' : IDL.Func([], [IDL.Vec(Person)], ['query']),
    'getPerson' : IDL.Func([IDL.Nat], [IDL.Opt(Person)], ['query']),
    'getPresentation' : IDL.Func([IDL.Nat], [IDL.Opt(Presentation)], ['query']),
    'getPresentationSlides' : IDL.Func([IDL.Nat], [IDL.Vec(Slide)], ['query']),
    'getPresentations' : IDL.Func([], [IDL.Vec(Presentation)], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getProjectMilestones' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProjectMilestone)],
        ['query'],
      ),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getSheet' : IDL.Func([IDL.Nat], [IDL.Opt(Sheet)], ['query']),
    'getSheetCells' : IDL.Func([IDL.Nat], [IDL.Vec(SheetCell)], ['query']),
    'getSheets' : IDL.Func([], [IDL.Vec(Sheet)], ['query']),
    'getTaskLists' : IDL.Func([], [IDL.Vec(TaskList)], ['query']),
    'getTasks' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'getUser' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
    'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getWorkspace' : IDL.Func([], [IDL.Opt(Workspace)], ['query']),
    'getWorkspaceMembers' : IDL.Func([], [IDL.Vec(AuthUser)], ['query']),
    'getWorkspaceSettings' : IDL.Func([], [WorkspaceSettings], ['query']),
    'isOnboarded' : IDL.Func([], [IDL.Bool], ['query']),
    'joinWithInviteCode' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(AuthUser)],
        [],
      ),
    'markAllNotificationsRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [AuthUser], []),
    'removeMember' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'removeMemberByPrincipal' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'renamePresentation' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(Presentation)],
        [],
      ),
    'renameSheet' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Sheet)], []),
    'reorderSlides' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat)],
        [IDL.Vec(Slide)],
        [],
      ),
    'sendDirectMessage' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [DirectMessage],
        [],
      ),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [Message], []),
    'setSheetCell' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [SheetCell],
        [],
      ),
    'toggleCalendarVisibility' : IDL.Func([IDL.Nat], [IDL.Opt(Calendar)], []),
    'toggleProjectMilestone' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ProjectMilestone)],
        [],
      ),
    'updateCalendarEvent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Bool, IDL.Text],
        [IDL.Opt(CalendarEvent)],
        [],
      ),
    'updateDocument' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Opt(Document)],
        [],
      ),
    'updateMember' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(Person)],
        [],
      ),
    'updateMyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateNote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Opt(Note)], []),
    'updatePersonStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Person)], []),
    'updateProject' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(Project)],
        [],
      ),
    'updateProjectMilestone' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Int)],
        [IDL.Opt(ProjectMilestone)],
        [],
      ),
    'updateSlide' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(Slide)],
        [],
      ),
    'updateTask' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Opt(IDL.Int),
          TaskPriority,
          TaskStatus,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Opt(Task)],
        [],
      ),
    'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [IDL.Opt(Task)], []),
    'updateUserSettings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [UserSettings],
        [],
      ),
    'updateWorkspaceSettings' : IDL.Func(
        [IDL.Text, IDL.Text],
        [WorkspaceSettings],
        [],
      ),
    'whoAmI' : IDL.Func([], [IDL.Principal], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };