/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEntry {
  'id' : bigint,
  'action' : string,
  'moduleName' : string,
  'userId' : string,
  'description' : string,
  'timestamp' : bigint,
}
export interface AuthUser {
  'id' : bigint,
  'title' : string,
  'principal' : [] | [Principal],
  'name' : string,
  'createdAt' : [] | [bigint],
  'role' : { 'member' : null } |
    { 'admin' : null } |
    { 'owner' : null } |
    { 'guest' : null },
  'email' : string,
  'avatarColor' : string,
  'department' : string,
  'lastLogin' : [] | [bigint],
}
export interface Calendar {
  'id' : bigint,
  'name' : string,
  'color' : string,
  'visible' : boolean,
}
export interface CalendarEvent {
  'id' : bigint,
  'startTime' : bigint,
  'title' : string,
  'endTime' : bigint,
  'allDay' : boolean,
  'color' : string,
  'description' : string,
  'calendarId' : bigint,
}
export interface Channel {
  'id' : bigint,
  'topic' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'workspaceId' : bigint,
}
export interface DirectMessage {
  'id' : bigint,
  'content' : string,
  'createdAt' : Timestamp,
  'toUserId' : UserId,
  'fromUserId' : UserId,
}
export interface Document {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'workspaceId' : bigint,
  'folderId' : [] | [bigint],
}
export interface Folder {
  'id' : bigint,
  'name' : string,
  'workspaceId' : bigint,
  'parentId' : [] | [bigint],
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'channelId' : bigint,
  'authorId' : UserId,
  'createdAt' : Timestamp,
}
export interface Note {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'folderId' : [] | [bigint],
}
export interface NoteFolder {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
}
export interface Notification {
  'id' : bigint,
  'title' : string,
  'notifType' : { 'update' : null } |
    { 'mention' : null } |
    { 'activity' : null },
  'body' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'sourceId' : [] | [bigint],
  'isRead' : boolean,
  'sourceType' : [] | [string],
}
export interface Person {
  'id' : bigint,
  'status' : string,
  'avatarInitials' : string,
  'name' : string,
  'createdAt' : bigint,
  'role' : string,
  'email' : string,
  'department' : string,
}
export interface Presentation {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
}
export interface Project {
  'id' : bigint,
  'status' : string,
  'ownerId' : string,
  'name' : string,
  'createdAt' : bigint,
  'color' : string,
  'description' : string,
  'updatedAt' : bigint,
}
export interface ProjectMilestone {
  'id' : bigint,
  'title' : string,
  'completed' : boolean,
  'dueDate' : [] | [bigint],
  'projectId' : bigint,
}
export interface Sheet {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
}
export interface SheetCell {
  'col' : bigint,
  'row' : bigint,
  'value' : string,
  'sheetId' : bigint,
}
export interface Slide {
  'id' : bigint,
  'visualType' : string,
  'title' : string,
  'content' : string,
  'presentationId' : bigint,
  'position' : bigint,
}
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'title' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'dueDate' : [] | [Timestamp],
  'description' : string,
  'assigneeIds' : Array<UserId>,
  'projectId' : [] | [bigint],
  'priority' : TaskPriority,
  'listId' : bigint,
}
export interface TaskList {
  'id' : bigint,
  'name' : string,
  'projectId' : [] | [bigint],
  'workspaceId' : bigint,
  'isPersonal' : boolean,
}
export type TaskPriority = { 'low' : null } |
  { 'normal' : null } |
  { 'high' : null } |
  { 'urgent' : null };
export type TaskStatus = { 'done' : null } |
  { 'blocked' : null } |
  { 'todo' : null } |
  { 'inProgress' : null };
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'title' : string,
  'name' : string,
  'role' : { 'member' : null } |
    { 'admin' : null } |
    { 'owner' : null } |
    { 'guest' : null },
  'email' : string,
  'avatarColor' : string,
  'department' : string,
}
export type UserId = bigint;
export interface UserSettings {
  'theme' : string,
  'notificationsEnabled' : boolean,
  'displayName' : string,
  'email' : string,
}
export interface Workspace {
  'id' : bigint,
  'ownerId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'memberIds' : Array<UserId>,
}
export interface WorkspaceSettings { 'name' : string, 'description' : string }
export interface _SERVICE {
  'addActivity' : ActorMethod<[string, string, string, string], ActivityEntry>,
  'addPerson' : ActorMethod<[string, string, string, string, string], Person>,
  'assignMemberRole' : ActorMethod<[Principal, string], boolean>,
  'clearSheetCell' : ActorMethod<[bigint, bigint, bigint], boolean>,
  'completeOnboarding' : ActorMethod<
    [string, string, string, string, string],
    AuthUser
  >,
  'createCalendar' : ActorMethod<[string, string], Calendar>,
  'createCalendarEvent' : ActorMethod<
    [string, string, bigint, bigint, boolean, string, bigint],
    CalendarEvent
  >,
  'createChannel' : ActorMethod<[string, string], Channel>,
  'createDocument' : ActorMethod<[string, [] | [bigint]], Document>,
  'createNote' : ActorMethod<[string, [] | [bigint]], Note>,
  'createNoteFolder' : ActorMethod<[string], NoteFolder>,
  'createPresentation' : ActorMethod<[string], Presentation>,
  'createProject' : ActorMethod<
    [string, string, string, string, string],
    Project
  >,
  'createProjectMilestone' : ActorMethod<
    [bigint, string, [] | [bigint]],
    ProjectMilestone
  >,
  'createSheet' : ActorMethod<[string], Sheet>,
  'createSlide' : ActorMethod<[bigint, bigint, string, string, string], Slide>,
  'createTask' : ActorMethod<
    [
      string,
      string,
      Array<bigint>,
      [] | [bigint],
      TaskPriority,
      TaskStatus,
      bigint,
      Array<string>,
      [] | [bigint],
    ],
    Task
  >,
  'deleteCalendarEvent' : ActorMethod<[bigint], boolean>,
  'deleteNote' : ActorMethod<[bigint], boolean>,
  'deleteNoteFolder' : ActorMethod<[bigint], boolean>,
  'deletePresentation' : ActorMethod<[bigint], boolean>,
  'deleteProject' : ActorMethod<[bigint], boolean>,
  'deleteProjectMilestone' : ActorMethod<[bigint], boolean>,
  'deleteSheet' : ActorMethod<[bigint], boolean>,
  'deleteSlide' : ActorMethod<[bigint], boolean>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getActivityFeed' : ActorMethod<[[] | [bigint]], Array<ActivityEntry>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCalendarEvents' : ActorMethod<[[] | [bigint]], Array<CalendarEvent>>,
  'getCalendars' : ActorMethod<[], Array<Calendar>>,
  'getChannels' : ActorMethod<[], Array<Channel>>,
  'getDirectMessages' : ActorMethod<[bigint, bigint], Array<DirectMessage>>,
  'getDocument' : ActorMethod<[bigint], [] | [Document]>,
  'getDocuments' : ActorMethod<[[] | [bigint]], Array<Document>>,
  'getFolders' : ActorMethod<[], Array<Folder>>,
  'getMe' : ActorMethod<[], [] | [AuthUser]>,
  'getMessages' : ActorMethod<[bigint], Array<Message>>,
  'getNote' : ActorMethod<[bigint], [] | [Note]>,
  'getNoteFolders' : ActorMethod<[], Array<NoteFolder>>,
  'getNotes' : ActorMethod<[[] | [bigint]], Array<Note>>,
  'getNotifications' : ActorMethod<[bigint], Array<Notification>>,
  'getPeople' : ActorMethod<[], Array<Person>>,
  'getPerson' : ActorMethod<[bigint], [] | [Person]>,
  'getPresentation' : ActorMethod<[bigint], [] | [Presentation]>,
  'getPresentationSlides' : ActorMethod<[bigint], Array<Slide>>,
  'getPresentations' : ActorMethod<[], Array<Presentation>>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'getProjectMilestones' : ActorMethod<[bigint], Array<ProjectMilestone>>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getSheet' : ActorMethod<[bigint], [] | [Sheet]>,
  'getSheetCells' : ActorMethod<[bigint], Array<SheetCell>>,
  'getSheets' : ActorMethod<[], Array<Sheet>>,
  'getTaskLists' : ActorMethod<[], Array<TaskList>>,
  'getTasks' : ActorMethod<[bigint], Array<Task>>,
  'getUser' : ActorMethod<[bigint], [] | [User]>,
  'getUserSettings' : ActorMethod<[], UserSettings>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'getWorkspace' : ActorMethod<[], [] | [Workspace]>,
  'getWorkspaceMembers' : ActorMethod<[], Array<AuthUser>>,
  'getWorkspaceSettings' : ActorMethod<[], WorkspaceSettings>,
  'isOnboarded' : ActorMethod<[], boolean>,
  'joinWithInviteCode' : ActorMethod<[string, string, string], [] | [AuthUser]>,
  'markAllNotificationsRead' : ActorMethod<[bigint], boolean>,
  'markNotificationRead' : ActorMethod<[bigint], boolean>,
  'registerUser' : ActorMethod<[string, string, string], AuthUser>,
  'removeMember' : ActorMethod<[bigint], boolean>,
  'removeMemberByPrincipal' : ActorMethod<[Principal], boolean>,
  'renamePresentation' : ActorMethod<[bigint, string], [] | [Presentation]>,
  'renameSheet' : ActorMethod<[bigint, string], [] | [Sheet]>,
  'reorderSlides' : ActorMethod<[bigint, Array<bigint>], Array<Slide>>,
  'sendDirectMessage' : ActorMethod<[bigint, bigint, string], DirectMessage>,
  'sendMessage' : ActorMethod<[bigint, string, bigint], Message>,
  'setSheetCell' : ActorMethod<[bigint, bigint, bigint, string], SheetCell>,
  'toggleCalendarVisibility' : ActorMethod<[bigint], [] | [Calendar]>,
  'toggleProjectMilestone' : ActorMethod<[bigint], [] | [ProjectMilestone]>,
  'updateCalendarEvent' : ActorMethod<
    [bigint, string, string, bigint, bigint, boolean, string],
    [] | [CalendarEvent]
  >,
  'updateDocument' : ActorMethod<[bigint, string, string], [] | [Document]>,
  'updateMember' : ActorMethod<
    [bigint, string, string, string, string],
    [] | [Person]
  >,
  'updateMyProfile' : ActorMethod<[string, string, string, string], boolean>,
  'updateNote' : ActorMethod<[bigint, string, string], [] | [Note]>,
  'updatePersonStatus' : ActorMethod<[bigint, string], [] | [Person]>,
  'updateProject' : ActorMethod<
    [bigint, string, string, string],
    [] | [Project]
  >,
  'updateProjectMilestone' : ActorMethod<
    [bigint, string, [] | [bigint]],
    [] | [ProjectMilestone]
  >,
  'updateSlide' : ActorMethod<[bigint, string, string, string], [] | [Slide]>,
  'updateTask' : ActorMethod<
    [
      bigint,
      string,
      string,
      Array<bigint>,
      [] | [bigint],
      TaskPriority,
      TaskStatus,
      Array<string>,
    ],
    [] | [Task]
  >,
  'updateTaskStatus' : ActorMethod<[bigint, TaskStatus], [] | [Task]>,
  'updateUserSettings' : ActorMethod<
    [string, string, boolean, string],
    UserSettings
  >,
  'updateWorkspaceSettings' : ActorMethod<[string, string], WorkspaceSettings>,
  'whoAmI' : ActorMethod<[], Principal>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];