/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ActivityEntry {
    id: bigint;
    action: string;
    moduleName: string;
    userId: string;
    description: string;
    timestamp: bigint;
}
export type Timestamp = bigint;
export interface AuthUser {
    id: bigint;
    title: string;
    principal?: Principal;
    name: string;
    createdAt?: bigint;
    role: Variant_member_admin_owner_guest;
    email: string;
    avatarColor: string;
    department: string;
    lastLogin?: bigint;
}
export interface Document {
    id: bigint;
    title: string;
    content: string;
    authorId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    workspaceId: bigint;
    folderId?: bigint;
}
export interface Task {
    id: bigint;
    status: TaskStatus;
    title: string;
    createdAt: Timestamp;
    tags: Array<string>;
    dueDate?: Timestamp;
    description: string;
    assigneeIds: Array<UserId>;
    projectId?: bigint;
    priority: TaskPriority;
    listId: bigint;
}
export interface NoteFolder {
    id: bigint;
    name: string;
    createdAt: bigint;
}
export interface Calendar {
    id: bigint;
    name: string;
    color: string;
    visible: boolean;
}
export interface Folder {
    id: bigint;
    name: string;
    workspaceId: bigint;
    parentId?: bigint;
}
export interface Note {
    id: bigint;
    title: string;
    content: string;
    createdAt: bigint;
    updatedAt: bigint;
    folderId?: bigint;
}
export interface DirectMessage {
    id: bigint;
    content: string;
    createdAt: Timestamp;
    toUserId: UserId;
    fromUserId: UserId;
}
export interface Slide {
    id: bigint;
    visualType: string;
    title: string;
    content: string;
    presentationId: bigint;
    position: bigint;
}
export interface Sheet {
    id: bigint;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
}
export interface Workspace {
    id: bigint;
    ownerId: UserId;
    name: string;
    createdAt: Timestamp;
    memberIds: Array<UserId>;
}
export interface User {
    id: UserId;
    title: string;
    name: string;
    role: Variant_member_admin_owner_guest;
    email: string;
    avatarColor: string;
    department: string;
}
export interface Channel {
    id: bigint;
    topic: string;
    name: string;
    createdAt: Timestamp;
    workspaceId: bigint;
}
export interface Presentation {
    id: bigint;
    title: string;
    createdAt: bigint;
    updatedAt: bigint;
}
export type UserId = bigint;
export interface CalendarEvent {
    id: bigint;
    startTime: bigint;
    title: string;
    endTime: bigint;
    allDay: boolean;
    color: string;
    description: string;
    calendarId: bigint;
}
export interface Notification {
    id: bigint;
    title: string;
    notifType: Variant_update_mention_activity;
    body: string;
    userId: UserId;
    createdAt: Timestamp;
    sourceId?: bigint;
    isRead: boolean;
    sourceType?: string;
}
export interface Message {
    id: bigint;
    content: string;
    channelId: bigint;
    authorId: UserId;
    createdAt: Timestamp;
}
export interface SheetCell {
    col: bigint;
    row: bigint;
    value: string;
    sheetId: bigint;
}
export interface WorkspaceSettings {
    name: string;
    description: string;
}
export interface UserSettings {
    theme: string;
    notificationsEnabled: boolean;
    displayName: string;
    email: string;
}
export interface ProjectMilestone {
    id: bigint;
    title: string;
    completed: boolean;
    dueDate?: bigint;
    projectId: bigint;
}
export interface Project {
    id: bigint;
    status: string;
    ownerId: string;
    name: string;
    createdAt: bigint;
    color: string;
    description: string;
    updatedAt: bigint;
}
export interface TaskList {
    id: bigint;
    name: string;
    projectId?: bigint;
    workspaceId: bigint;
    isPersonal: boolean;
}
export interface Person {
    id: bigint;
    status: string;
    avatarInitials: string;
    name: string;
    createdAt: bigint;
    role: string;
    email: string;
    department: string;
}
export enum TaskPriority {
    low = "low",
    normal = "normal",
    high = "high",
    urgent = "urgent"
}
export enum TaskStatus {
    done = "done",
    blocked = "blocked",
    todo = "todo",
    inProgress = "inProgress"
}
export enum Variant_member_admin_owner_guest {
    member = "member",
    admin = "admin",
    owner = "owner",
    guest = "guest"
}
export enum Variant_update_mention_activity {
    update = "update",
    mention = "mention",
    activity = "activity"
}
export interface backendInterface {
    addActivity(module: string, action: string, description: string, userId: string): Promise<ActivityEntry>;
    addPerson(name: string, role: string, email: string, department: string, avatarInitials: string): Promise<Person>;
    assignMemberRole(targetPrincipal: Principal, role: string): Promise<boolean>;
    clearSheetCell(sheetId: bigint, row: bigint, col: bigint): Promise<boolean>;
    completeOnboarding(name: string, workspaceName: string, title: string, department: string, avatarColor: string): Promise<AuthUser>;
    createCalendar(name: string, color: string): Promise<Calendar>;
    createCalendarEvent(title: string, description: string, startTime: bigint, endTime: bigint, allDay: boolean, color: string, calendarId: bigint): Promise<CalendarEvent>;
    createChannel(name: string, topic: string): Promise<Channel>;
    createDocument(title: string, folderId: bigint | null): Promise<Document>;
    createNote(title: string, folderId: bigint | null): Promise<Note>;
    createNoteFolder(name: string): Promise<NoteFolder>;
    createPresentation(title: string): Promise<Presentation>;
    createProject(name: string, description: string, status: string, color: string, ownerId: string): Promise<Project>;
    createProjectMilestone(projectId: bigint, title: string, dueDate: bigint | null): Promise<ProjectMilestone>;
    createSheet(name: string): Promise<Sheet>;
    createSlide(presentationId: bigint, position: bigint, title: string, content: string, visualType: string): Promise<Slide>;
    createTask(title: string, description: string, assigneeIds: Array<bigint>, dueDate: bigint | null, priority: TaskPriority, status: TaskStatus, listId: bigint, tags: Array<string>, projectId: bigint | null): Promise<Task>;
    deleteCalendarEvent(id: bigint): Promise<boolean>;
    deleteNote(id: bigint): Promise<boolean>;
    deleteNoteFolder(id: bigint): Promise<boolean>;
    deletePresentation(id: bigint): Promise<boolean>;
    deleteProject(id: bigint): Promise<boolean>;
    deleteProjectMilestone(id: bigint): Promise<boolean>;
    deleteSheet(id: bigint): Promise<boolean>;
    deleteSlide(id: bigint): Promise<boolean>;
    generateInviteCode(): Promise<string>;
    getActivityFeed(limit: bigint | null): Promise<Array<ActivityEntry>>;
    getAllTasks(): Promise<Array<Task>>;
    getCalendarEvents(calendarId: bigint | null): Promise<Array<CalendarEvent>>;
    getCalendars(): Promise<Array<Calendar>>;
    getChannels(): Promise<Array<Channel>>;
    getDirectMessages(userId: bigint, withUserId: bigint): Promise<Array<DirectMessage>>;
    getDocument(id: bigint): Promise<Document | null>;
    getDocuments(folderId: bigint | null): Promise<Array<Document>>;
    getFolders(): Promise<Array<Folder>>;
    getMe(): Promise<AuthUser | null>;
    getMessages(channelId: bigint): Promise<Array<Message>>;
    getNote(id: bigint): Promise<Note | null>;
    getNoteFolders(): Promise<Array<NoteFolder>>;
    getNotes(folderId: bigint | null): Promise<Array<Note>>;
    getNotifications(userId: bigint): Promise<Array<Notification>>;
    getPeople(): Promise<Array<Person>>;
    getPerson(id: bigint): Promise<Person | null>;
    getPresentation(id: bigint): Promise<Presentation | null>;
    getPresentationSlides(presentationId: bigint): Promise<Array<Slide>>;
    getPresentations(): Promise<Array<Presentation>>;
    getProject(id: bigint): Promise<Project | null>;
    getProjectMilestones(projectId: bigint): Promise<Array<ProjectMilestone>>;
    getProjects(): Promise<Array<Project>>;
    getSheet(id: bigint): Promise<Sheet | null>;
    getSheetCells(sheetId: bigint): Promise<Array<SheetCell>>;
    getSheets(): Promise<Array<Sheet>>;
    getTaskLists(): Promise<Array<TaskList>>;
    getTasks(listId: bigint): Promise<Array<Task>>;
    getUser(id: bigint): Promise<User | null>;
    getUserSettings(): Promise<UserSettings>;
    getUsers(): Promise<Array<User>>;
    getWorkspace(): Promise<Workspace | null>;
    getWorkspaceMembers(): Promise<Array<AuthUser>>;
    getWorkspaceSettings(): Promise<WorkspaceSettings>;
    isOnboarded(): Promise<boolean>;
    joinWithInviteCode(code: string, name: string, avatarColor: string): Promise<AuthUser | null>;
    markAllNotificationsRead(userId: bigint): Promise<boolean>;
    markNotificationRead(id: bigint): Promise<boolean>;
    registerUser(name: string, email: string, avatarColor: string): Promise<AuthUser>;
    removeMember(id: bigint): Promise<boolean>;
    removeMemberByPrincipal(targetPrincipal: Principal): Promise<boolean>;
    renamePresentation(id: bigint, title: string): Promise<Presentation | null>;
    renameSheet(id: bigint, name: string): Promise<Sheet | null>;
    reorderSlides(presentationId: bigint, orderedIds: Array<bigint>): Promise<Array<Slide>>;
    sendDirectMessage(fromUserId: bigint, toUserId: bigint, content: string): Promise<DirectMessage>;
    sendMessage(channelId: bigint, content: string, authorId: bigint): Promise<Message>;
    setSheetCell(sheetId: bigint, row: bigint, col: bigint, value: string): Promise<SheetCell>;
    toggleCalendarVisibility(id: bigint): Promise<Calendar | null>;
    toggleProjectMilestone(id: bigint): Promise<ProjectMilestone | null>;
    updateCalendarEvent(id: bigint, title: string, description: string, startTime: bigint, endTime: bigint, allDay: boolean, color: string): Promise<CalendarEvent | null>;
    updateDocument(id: bigint, title: string, content: string): Promise<Document | null>;
    updateMember(id: bigint, name: string, role: string, email: string, department: string): Promise<Person | null>;
    updateMyProfile(name: string, title: string, department: string, avatarColor: string): Promise<boolean>;
    updateNote(id: bigint, title: string, content: string): Promise<Note | null>;
    updatePersonStatus(id: bigint, status: string): Promise<Person | null>;
    updateProject(id: bigint, name: string, description: string, status: string): Promise<Project | null>;
    updateProjectMilestone(id: bigint, title: string, dueDate: bigint | null): Promise<ProjectMilestone | null>;
    updateSlide(id: bigint, title: string, content: string, visualType: string): Promise<Slide | null>;
    updateTask(id: bigint, title: string, description: string, assigneeIds: Array<bigint>, dueDate: bigint | null, priority: TaskPriority, status: TaskStatus, tags: Array<string>): Promise<Task | null>;
    updateTaskStatus(id: bigint, status: TaskStatus): Promise<Task | null>;
    updateUserSettings(displayName: string, email: string, notificationsEnabled: boolean, theme: string): Promise<UserSettings>;
    updateWorkspaceSettings(name: string, description: string): Promise<WorkspaceSettings>;
    whoAmI(): Promise<Principal>;
}
import type { AuthUser as _AuthUser, Calendar as _Calendar, CalendarEvent as _CalendarEvent, Document as _Document, Folder as _Folder, Note as _Note, Notification as _Notification, Person as _Person, Presentation as _Presentation, Project as _Project, ProjectMilestone as _ProjectMilestone, Sheet as _Sheet, Slide as _Slide, Task as _Task, TaskList as _TaskList, TaskPriority as _TaskPriority, TaskStatus as _TaskStatus, Timestamp as _Timestamp, User as _User, UserId as _UserId, Workspace as _Workspace } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addActivity(arg0: string, arg1: string, arg2: string, arg3: string): Promise<ActivityEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivity(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivity(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addPerson(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Person> {
        if (this.processError) {
            try {
                const result = await this.actor.addPerson(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPerson(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignMemberRole(arg0: Principal, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignMemberRole(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignMemberRole(arg0, arg1);
            return result;
        }
    }
    async clearSheetCell(arg0: bigint, arg1: bigint, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearSheetCell(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearSheetCell(arg0, arg1, arg2);
            return result;
        }
    }
    async completeOnboarding(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<AuthUser> {
        if (this.processError) {
            try {
                const result = await this.actor.completeOnboarding(arg0, arg1, arg2, arg3, arg4);
                return from_candid_AuthUser_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeOnboarding(arg0, arg1, arg2, arg3, arg4);
            return from_candid_AuthUser_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCalendar(arg0: string, arg1: string): Promise<Calendar> {
        if (this.processError) {
            try {
                const result = await this.actor.createCalendar(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCalendar(arg0, arg1);
            return result;
        }
    }
    async createCalendarEvent(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: boolean, arg5: string, arg6: bigint): Promise<CalendarEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.createCalendarEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCalendarEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createChannel(arg0: string, arg1: string): Promise<Channel> {
        if (this.processError) {
            try {
                const result = await this.actor.createChannel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChannel(arg0, arg1);
            return result;
        }
    }
    async createDocument(arg0: string, arg1: bigint | null): Promise<Document> {
        if (this.processError) {
            try {
                const result = await this.actor.createDocument(arg0, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Document_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDocument(arg0, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Document_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNote(arg0: string, arg1: bigint | null): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Note_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Note_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNoteFolder(arg0: string): Promise<NoteFolder> {
        if (this.processError) {
            try {
                const result = await this.actor.createNoteFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNoteFolder(arg0);
            return result;
        }
    }
    async createPresentation(arg0: string): Promise<Presentation> {
        if (this.processError) {
            try {
                const result = await this.actor.createPresentation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPresentation(arg0);
            return result;
        }
    }
    async createProject(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createProjectMilestone(arg0: bigint, arg1: string, arg2: bigint | null): Promise<ProjectMilestone> {
        if (this.processError) {
            try {
                const result = await this.actor.createProjectMilestone(arg0, arg1, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2));
                return from_candid_ProjectMilestone_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProjectMilestone(arg0, arg1, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2));
            return from_candid_ProjectMilestone_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSheet(arg0: string): Promise<Sheet> {
        if (this.processError) {
            try {
                const result = await this.actor.createSheet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSheet(arg0);
            return result;
        }
    }
    async createSlide(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string): Promise<Slide> {
        if (this.processError) {
            try {
                const result = await this.actor.createSlide(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSlide(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: Array<bigint>, arg3: bigint | null, arg4: TaskPriority, arg5: TaskStatus, arg6: bigint, arg7: Array<string>, arg8: bigint | null): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), to_candid_TaskPriority_n15(this._uploadFile, this._downloadFile, arg4), to_candid_TaskStatus_n17(this._uploadFile, this._downloadFile, arg5), arg6, arg7, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg8));
                return from_candid_Task_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), to_candid_TaskPriority_n15(this._uploadFile, this._downloadFile, arg4), to_candid_TaskStatus_n17(this._uploadFile, this._downloadFile, arg5), arg6, arg7, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg8));
            return from_candid_Task_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCalendarEvent(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCalendarEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCalendarEvent(arg0);
            return result;
        }
    }
    async deleteNote(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async deleteNoteFolder(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNoteFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNoteFolder(arg0);
            return result;
        }
    }
    async deletePresentation(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePresentation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePresentation(arg0);
            return result;
        }
    }
    async deleteProject(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteProjectMilestone(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProjectMilestone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProjectMilestone(arg0);
            return result;
        }
    }
    async deleteSheet(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSheet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSheet(arg0);
            return result;
        }
    }
    async deleteSlide(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSlide(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSlide(arg0);
            return result;
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getActivityFeed(arg0: bigint | null): Promise<Array<ActivityEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityFeed(to_candid_opt_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityFeed(to_candid_opt_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCalendarEvents(arg0: bigint | null): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCalendarEvents(to_candid_opt_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCalendarEvents(to_candid_opt_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCalendars(): Promise<Array<Calendar>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCalendars();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCalendars();
            return result;
        }
    }
    async getChannels(): Promise<Array<Channel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannels();
            return result;
        }
    }
    async getDirectMessages(arg0: bigint, arg1: bigint): Promise<Array<DirectMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDirectMessages(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDirectMessages(arg0, arg1);
            return result;
        }
    }
    async getDocument(arg0: bigint): Promise<Document | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocuments(arg0: bigint | null): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocuments(to_candid_opt_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocuments(to_candid_opt_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFolders(): Promise<Array<Folder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFolders();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFolders();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMe(): Promise<AuthUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMe();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMe();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getNote(arg0: bigint): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNote(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNote(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNoteFolders(): Promise<Array<NoteFolder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNoteFolders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNoteFolders();
            return result;
        }
    }
    async getNotes(arg0: bigint | null): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotes(to_candid_opt_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotes(to_candid_opt_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(arg0: bigint): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPeople(): Promise<Array<Person>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPeople();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPeople();
            return result;
        }
    }
    async getPerson(arg0: bigint): Promise<Person | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerson(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerson(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPresentation(arg0: bigint): Promise<Presentation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPresentation(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPresentation(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPresentationSlides(arg0: bigint): Promise<Array<Slide>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPresentationSlides(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPresentationSlides(arg0);
            return result;
        }
    }
    async getPresentations(): Promise<Array<Presentation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPresentations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPresentations();
            return result;
        }
    }
    async getProject(arg0: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectMilestones(arg0: bigint): Promise<Array<ProjectMilestone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectMilestones(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectMilestones(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects();
            return result;
        }
    }
    async getSheet(arg0: bigint): Promise<Sheet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSheet(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSheet(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSheetCells(arg0: bigint): Promise<Array<SheetCell>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSheetCells(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSheetCells(arg0);
            return result;
        }
    }
    async getSheets(): Promise<Array<Sheet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSheets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSheets();
            return result;
        }
    }
    async getTaskLists(): Promise<Array<TaskList>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskLists();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskLists();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasks(arg0: bigint): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: bigint): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSettings(): Promise<UserSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSettings();
            return result;
        }
    }
    async getUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkspace(): Promise<Workspace | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkspace();
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkspace();
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkspaceMembers(): Promise<Array<AuthUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkspaceMembers();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkspaceMembers();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkspaceSettings(): Promise<WorkspaceSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkspaceSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkspaceSettings();
            return result;
        }
    }
    async isOnboarded(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOnboarded();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOnboarded();
            return result;
        }
    }
    async joinWithInviteCode(arg0: string, arg1: string, arg2: string): Promise<AuthUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.joinWithInviteCode(arg0, arg1, arg2);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinWithInviteCode(arg0, arg1, arg2);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsRead(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead(arg0);
            return result;
        }
    }
    async markNotificationRead(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string): Promise<AuthUser> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2);
                return from_candid_AuthUser_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2);
            return from_candid_AuthUser_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeMember(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMember(arg0);
            return result;
        }
    }
    async removeMemberByPrincipal(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMemberByPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMemberByPrincipal(arg0);
            return result;
        }
    }
    async renamePresentation(arg0: bigint, arg1: string): Promise<Presentation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.renamePresentation(arg0, arg1);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renamePresentation(arg0, arg1);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async renameSheet(arg0: bigint, arg1: string): Promise<Sheet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.renameSheet(arg0, arg1);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameSheet(arg0, arg1);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async reorderSlides(arg0: bigint, arg1: Array<bigint>): Promise<Array<Slide>> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderSlides(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderSlides(arg0, arg1);
            return result;
        }
    }
    async sendDirectMessage(arg0: bigint, arg1: bigint, arg2: string): Promise<DirectMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.sendDirectMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendDirectMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async sendMessage(arg0: bigint, arg1: string, arg2: bigint): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async setSheetCell(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string): Promise<SheetCell> {
        if (this.processError) {
            try {
                const result = await this.actor.setSheetCell(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSheetCell(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async toggleCalendarVisibility(arg0: bigint): Promise<Calendar | null> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCalendarVisibility(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCalendarVisibility(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleProjectMilestone(arg0: bigint): Promise<ProjectMilestone | null> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleProjectMilestone(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleProjectMilestone(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCalendarEvent(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: boolean, arg6: string): Promise<CalendarEvent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCalendarEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCalendarEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDocument(arg0: bigint, arg1: string, arg2: string): Promise<Document | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDocument(arg0, arg1, arg2);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDocument(arg0, arg1, arg2);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMember(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Person | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMember(arg0, arg1, arg2, arg3, arg4);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMember(arg0, arg1, arg2, arg3, arg4);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyProfile(arg0: string, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateNote(arg0: bigint, arg1: string, arg2: string): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, arg1, arg2);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, arg1, arg2);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePersonStatus(arg0: bigint, arg1: string): Promise<Person | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePersonStatus(arg0, arg1);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePersonStatus(arg0, arg1);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProject(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, arg2, arg3);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, arg2, arg3);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProjectMilestone(arg0: bigint, arg1: string, arg2: bigint | null): Promise<ProjectMilestone | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectMilestone(arg0, arg1, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2));
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectMilestone(arg0, arg1, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2));
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSlide(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<Slide | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSlide(arg0, arg1, arg2, arg3);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSlide(arg0, arg1, arg2, arg3);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTask(arg0: bigint, arg1: string, arg2: string, arg3: Array<bigint>, arg4: bigint | null, arg5: TaskPriority, arg6: TaskStatus, arg7: Array<string>): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), to_candid_TaskPriority_n15(this._uploadFile, this._downloadFile, arg5), to_candid_TaskStatus_n17(this._uploadFile, this._downloadFile, arg6), arg7);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), to_candid_TaskPriority_n15(this._uploadFile, this._downloadFile, arg5), to_candid_TaskStatus_n17(this._uploadFile, this._downloadFile, arg6), arg7);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTaskStatus(arg0: bigint, arg1: TaskStatus): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserSettings(arg0: string, arg1: string, arg2: boolean, arg3: string): Promise<UserSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserSettings(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserSettings(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateWorkspaceSettings(arg0: string, arg1: string): Promise<WorkspaceSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkspaceSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkspaceSettings(arg0, arg1);
            return result;
        }
    }
    async whoAmI(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.whoAmI();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.whoAmI();
            return result;
        }
    }
}
function from_candid_AuthUser_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthUser): AuthUser {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Document_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Document {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Folder_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Folder): Folder {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Note_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Note {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectMilestone_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectMilestone): ProjectMilestone {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_TaskList_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskList): TaskList {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_TaskPriority_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPriority): TaskPriority {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_User_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Document]): Document | null {
    return value.length === 0 ? null : from_candid_Document_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AuthUser]): AuthUser | null {
    return value.length === 0 ? null : from_candid_AuthUser_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Note]): Note | null {
    return value.length === 0 ? null : from_candid_Note_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Person]): Person | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Presentation]): Presentation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sheet]): Sheet | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Workspace]): Workspace | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Calendar]): Calendar | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProjectMilestone]): ProjectMilestone | null {
    return value.length === 0 ? null : from_candid_ProjectMilestone_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CalendarEvent]): CalendarEvent | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Slide]): Slide | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    createdAt: bigint;
    updatedAt: bigint;
    folderId: [] | [bigint];
}): {
    id: bigint;
    title: string;
    content: string;
    createdAt: bigint;
    updatedAt: bigint;
    folderId?: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        folderId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.folderId))
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    completed: boolean;
    dueDate: [] | [bigint];
    projectId: bigint;
}): {
    id: bigint;
    title: string;
    completed: boolean;
    dueDate?: bigint;
    projectId: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.dueDate)),
        projectId: value.projectId
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    principal: [] | [Principal];
    name: string;
    createdAt: [] | [bigint];
    role: {
        member: null;
    } | {
        admin: null;
    } | {
        owner: null;
    } | {
        guest: null;
    };
    email: string;
    avatarColor: string;
    department: string;
    lastLogin: [] | [bigint];
}): {
    id: bigint;
    title: string;
    principal?: Principal;
    name: string;
    createdAt?: bigint;
    role: Variant_member_admin_owner_guest;
    email: string;
    avatarColor: string;
    department: string;
    lastLogin?: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        principal: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.principal)),
        name: value.name,
        createdAt: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.createdAt)),
        role: from_candid_variant_n5(_uploadFile, _downloadFile, value.role),
        email: value.email,
        avatarColor: value.avatarColor,
        department: value.department,
        lastLogin: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.lastLogin))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    title: string;
    createdAt: _Timestamp;
    tags: Array<string>;
    dueDate: [] | [_Timestamp];
    description: string;
    assigneeIds: Array<_UserId>;
    projectId: [] | [bigint];
    priority: _TaskPriority;
    listId: bigint;
}): {
    id: bigint;
    status: TaskStatus;
    title: string;
    createdAt: Timestamp;
    tags: Array<string>;
    dueDate?: Timestamp;
    description: string;
    assigneeIds: Array<UserId>;
    projectId?: bigint;
    priority: TaskPriority;
    listId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n21(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        tags: value.tags,
        dueDate: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description,
        assigneeIds: value.assigneeIds,
        projectId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.projectId)),
        priority: from_candid_TaskPriority_n24(_uploadFile, _downloadFile, value.priority),
        listId: value.listId
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    workspaceId: bigint;
    parentId: [] | [bigint];
}): {
    id: bigint;
    name: string;
    workspaceId: bigint;
    parentId?: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        workspaceId: value.workspaceId,
        parentId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.parentId))
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    notifType: {
        update: null;
    } | {
        mention: null;
    } | {
        activity: null;
    };
    body: string;
    userId: _UserId;
    createdAt: _Timestamp;
    sourceId: [] | [bigint];
    isRead: boolean;
    sourceType: [] | [string];
}): {
    id: bigint;
    title: string;
    notifType: Variant_update_mention_activity;
    body: string;
    userId: UserId;
    createdAt: Timestamp;
    sourceId?: bigint;
    isRead: boolean;
    sourceType?: string;
} {
    return {
        id: value.id,
        title: value.title,
        notifType: from_candid_variant_n38(_uploadFile, _downloadFile, value.notifType),
        body: value.body,
        userId: value.userId,
        createdAt: value.createdAt,
        sourceId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.sourceId)),
        isRead: value.isRead,
        sourceType: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.sourceType))
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    projectId: [] | [bigint];
    workspaceId: bigint;
    isPersonal: boolean;
}): {
    id: bigint;
    name: string;
    projectId?: bigint;
    workspaceId: bigint;
    isPersonal: boolean;
} {
    return {
        id: value.id,
        name: value.name,
        projectId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.projectId)),
        workspaceId: value.workspaceId,
        isPersonal: value.isPersonal
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    title: string;
    name: string;
    role: {
        member: null;
    } | {
        admin: null;
    } | {
        owner: null;
    } | {
        guest: null;
    };
    email: string;
    avatarColor: string;
    department: string;
}): {
    id: UserId;
    title: string;
    name: string;
    role: Variant_member_admin_owner_guest;
    email: string;
    avatarColor: string;
    department: string;
} {
    return {
        id: value.id,
        title: value.title,
        name: value.name,
        role: from_candid_variant_n5(_uploadFile, _downloadFile, value.role),
        email: value.email,
        avatarColor: value.avatarColor,
        department: value.department
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    authorId: _UserId;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    workspaceId: bigint;
    folderId: [] | [bigint];
}): {
    id: bigint;
    title: string;
    content: string;
    authorId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    workspaceId: bigint;
    folderId?: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        authorId: value.authorId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        workspaceId: value.workspaceId,
        folderId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.folderId))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    done: null;
} | {
    blocked: null;
} | {
    todo: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "done" in value ? TaskStatus.done : "blocked" in value ? TaskStatus.blocked : "todo" in value ? TaskStatus.todo : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    normal: null;
} | {
    high: null;
} | {
    urgent: null;
}): TaskPriority {
    return "low" in value ? TaskPriority.low : "normal" in value ? TaskPriority.normal : "high" in value ? TaskPriority.high : "urgent" in value ? TaskPriority.urgent : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    update: null;
} | {
    mention: null;
} | {
    activity: null;
}): Variant_update_mention_activity {
    return "update" in value ? Variant_update_mention_activity.update : "mention" in value ? Variant_update_mention_activity.mention : "activity" in value ? Variant_update_mention_activity.activity : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: null;
} | {
    admin: null;
} | {
    owner: null;
} | {
    guest: null;
}): Variant_member_admin_owner_guest {
    return "member" in value ? Variant_member_admin_owner_guest.member : "admin" in value ? Variant_member_admin_owner_guest.admin : "owner" in value ? Variant_member_admin_owner_guest.owner : "guest" in value ? Variant_member_admin_owner_guest.guest : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Array<Document> {
    return value.map((x)=>from_candid_Document_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Folder>): Array<Folder> {
    return value.map((x)=>from_candid_Folder_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Array<Note> {
    return value.map((x)=>from_candid_Note_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectMilestone>): Array<ProjectMilestone> {
    return value.map((x)=>from_candid_ProjectMilestone_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskList>): Array<TaskList> {
    return value.map((x)=>from_candid_TaskList_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuthUser>): Array<AuthUser> {
    return value.map((x)=>from_candid_AuthUser_n1(_uploadFile, _downloadFile, x));
}
function to_candid_TaskPriority_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): _TaskPriority {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): {
    low: null;
} | {
    normal: null;
} | {
    high: null;
} | {
    urgent: null;
} {
    return value == TaskPriority.low ? {
        low: null
    } : value == TaskPriority.normal ? {
        normal: null
    } : value == TaskPriority.high ? {
        high: null
    } : value == TaskPriority.urgent ? {
        urgent: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    done: null;
} | {
    blocked: null;
} | {
    todo: null;
} | {
    inProgress: null;
} {
    return value == TaskStatus.done ? {
        done: null
    } : value == TaskStatus.blocked ? {
        blocked: null
    } : value == TaskStatus.todo ? {
        todo: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
